#!/bin/sh
#
# Start the network....
#

case "$1" in
  start)
    echo "Starting network..."
    ifconfig eth0 up 192.168.0.123
    ;;
  stop)
    echo -n "Stopping network..."
    ifconfig eth0 down 192.168.0.123
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
